### ISSUE TITLE
Fix Errata for Release of fedramp1.0.0-oscal1.0.0

### ISSUE THREAD

**Issue by ohsh6o** [GSA/fedramp-automation#107]
# Describe the bug

- [X] Update [baseline referenced in `import-profile/@href` URI](https://github.com/GSA/fedramp-automation/blob/master/templates/ssp/xml/FedRAMP-SSP-OSCAL-Template.xml#L502-L508) pointing to outdated copy of baseline. (GSA/fedramp-automation#121)
- [x] Fix `@ns` attribute and perhaps registry items for attachments per FedRAMP OSCAL SSP guide.
- [x] Issues with the `response-point` alignment, requires other fixes, not just in SSP, tracked in GSA/fedramp-automation#108.
- [X] An OSCAL developer following current guidance from the NIST OSCAL and FedRAMP guidance in documentation would set the `security-sensitivity-level` like so. (GSA/fedramp-automation/#122)
- [x] Fix example SORN ID value that is awkward, even as an example, with the new prop syntax (`<prop ns="https://fedramp.gov/ns/oscal" name="sorn-id" class="pta" value="[No SORN ID]"/>`). (GSA/fedramp-automation#125)
- [X] Fix out of sync versions in baselines and templates before release. (GSA/fedramp-automation#124)

```xml
<system-security-plan xmlns="http://csrc.nist.gov/ns/oscal/1.0"
   uuid="8c000726-ba93-480d-a221-8cb60df10c24">
  <metadata />
  <system-characteristics>
    <security-sensitivity-level>moderate</security-sensitivity-level>
  <system-characteristics>
</system-security-plan>
```

Per previous discussion, it should be this.

```xml
<system-security-plan xmlns="http://csrc.nist.gov/ns/oscal/1.0"
   uuid="8c000726-ba93-480d-a221-8cb60df10c24">
  <metadata />
  <system-characteristics>
    <security-sensitivity-level>fips-199-moderate</security-sensitivity-level>
  <system-characteristics>
</system-security-plan>
```

# Who is the bug affecting?

Those using the documentation and reference examples to build their own OSCAL tooling and SSPs.

# What is affected by this bug?

Current, clear, and exemplary use of OSCAL for SSP models.

# When does this occur?

Always.

# How do we replicate the issue?

Open the repository and review the examples.
