### ISSUE TITLE
JAB Checklist References in Validations (source: 18F/fedramp-automation: 292)

### ISSUE THREAD

**Issue by danielnaab** [GSA/fedramp-automation#296]
Original issue: https://github.com/18F/fedramp-automation/issues/292

**Extended Description**
As a FedRAMP reviewer, to ensure I can see validation pre-checks organized accordingly to my role in the FART and the JAB, I would like to see validation messages and assertion views to be organized by either FART or JAB checklist styles.

**Preconditions**
- [ ] Spike analysis of JAB checklists and methodologies and how they potentially differ from the FART.

**Stories**
- [ ] Design FedRAMP JAB checklist metadata into validation rules
- [ ] Update existing rules
- [ ] Existing Schematron rules and style guide
- [ ] Add new assertion view to user interface

**Comment by aj-stein-gsa** [comment]
We are not going to move forward with the current web UI approach, so I will close out this issue for now. For those who reported this issue or are following it, follow [ADR 7](https://github.com/GSA/fedramp-automation/blob/9d4d487e8e5e103018afcd1307bbeb111ff88d3b/documents/adr/007-signal-unsupportent-content-in-github.md) for more details.
