### ISSUE TITLE
Render FedRAMP Package Documents in UI for Links OSCAL Doc Refs (source: 18F/fedramp-automation: 286)

### ISSUE THREAD

**Issue by danielnaab** [GSA/fedramp-automation#298]
Original issue: https://github.com/18F/fedramp-automation/issues/286

**Extended Description**
As a FedRAMP reviewer, in order to understand the context of missing or incorrect data in a FedRAMP document, I would like to see the SSP, SAP, SAR, and POA&Ms documents in a digestible format. I do not want to see the underlying OSCAL JSON or XML or YAML data.

**Stories**
- [ ] Design and architecture spike
- [ ] Implement metadata rendering
- [ ] Implement back-matter rendering
- [ ] Implement SSP rendering
- [ ] Implement SAP rendering
- [ ] Implement SAR rendering
- [ ] Implement POA&M rendering

**Comment by aj-stein-gsa** [comment]
We are not going to move forward with the current web UI approach, so I will close out this issue for now. For those who reported this issue or are following it, follow [ADR 7](https://github.com/GSA/fedramp-automation/blob/9d4d487e8e5e103018afcd1307bbeb111ff88d3b/documents/adr/007-signal-unsupportent-content-in-github.md) for more details.
