### ISSUE TITLE
Create screencast videos walking through install

### ISSUE THREAD

**Issue by aj-stein-gsa** [GSA/fedramp-automation#694]
# User Story

As a developer consuming, integrating, and/or customizing FedRAMP Automation Team tools, to best educate and train myself, I would like to have a quick screencast video created to show how to cover the container-based installation of the FedRAMP validation toolchain.

# Tasks

- [x] Draft a video design document, [an inspirational example](https://docs.google.com/document/d/1AN9AJNdHihUVSyh29BGMm_xWXbUGctyxFA4OnRC_cFw/edit#heading=h.qgmcvn6a30f7) from our wonderful comms team
- [x] Brief the comms review board on the document and planned content
- [x] Record a screencast of the installation to show the following steps:
  - [x] Install the container with `docker pull ...`
  - [x] Confirm correct installation by run the container with `docker run -it --rm --volume $(pwd):/data ghcr.io/gsa/fedramp-automation/validation-tools:latest --version`
  - [x] Guide developers and engineers to find more information about each subcommand with the following command: `docker run -it --rm --volume $(pwd):/data ghcr.io/gsa/fedramp-automation/validation-tools:latest --help`
  - [x] Guide developers and engineers to find more information about each subcommand with the a common subcommand help menu: `docker run -it --rm --volume $(pwd):/data ghcr.io/gsa/fedramp-automation/validation-tools:latest validate --help`
- [ ] Edit the video, if necessary, to comply with video (and audio, if applicable, but probably not) [Section 508 requirements](https://www.section508.gov/create/audio-video/) and additional [GSA requirements for video content](https://insite.gsa.gov/employee-resources/communications/visual-communications/video-approval-and-creation?term=video)
- [ ] Seek final approval from comms review board, FedRAMP, and relevant stakeholders in GSA leadership
- [ ] Embed the YouTube (or applicable hosting platform) HTML-based player into [the README for constraints tooling](https://github.com/GSA/fedramp-automation/blob/182bff086ad8aa3895179ef30c41c1adfc47e715/src/validations/README.md)

**Comment by aj-stein-gsa** [comment]
Hey @kyhu65867, I know we know we are doing this (and others on the FedRAMP Auto Team per standup today), but I thought it was important to put it on the board. Details on requirements and AC to follow. 😄

**Comment by aj-stein-gsa** [comment]
A lot to improve later today or tomorrow, @kyhu65867, but this is my first pass:

https://drive.google.com/file/d/10LqVSIWeQLbBfXr1e2R7fewFNr_u6heN/view?usp=sharing

Things to change:

1. Get rid of my avatar in the corner, yuck.
2. Good OPSEC: make sure my username does not show up in the top banner of the terminal (you can tell I changed it in the prompt).
3. Perhaps reconsider Zoom recording, still seems kind of grainy.

Here is the current version of the demo-magic script I tried:

https://gist.github.com/aj-stein-gsa/408e8b1b3eb44c0b400c089bfc9f78c7

I used the following command but still had to hit space to get it started, `-n` says don't wait for enter in some cases and `-w` waits for 10 seconds in this case. We can speed it up or slow it down.

```sh
 clear && sleep 15 && demo_video_01.sh -n -w 10
```

Let me know your further thoughts before adding it to the brief.

**Comment by aj-stein-gsa** [comment]
Take 2, with a slightly better demo-magic script updated in the Gist above. Had to use the screencapture (Cmd+Shift+5) in the OS to get this far and make it cleaner, as well change some of the terminal settings.

https://drive.google.com/file/d/10MHjRY2mtjK0O36GaeXvNfAHn6ct3FZe/view?usp=drive_link

Not sure how much of an improvement it is.

**Comment by aj-stein-gsa** [comment]
@kyhu65867 sent the brief (with demo) along for approval and review by @Marcia-Simms. We look forward to the feedback but will hold on that.

In the interim, Kylie and I will look into Articulate 360 and see if adding that or only using that for the video recording pipeline is a better fit. We can hold on this for now.

**Comment by aj-stein-gsa** [comment]
We need to look into software to annotate the video for accessibility purposes and integrate some feedback from Marcia Simms, so we will move this back into in progress and touch that up in short order and then ask for review. If it still has to wait, we will mark it as blocked.

**Comment by Marcia-Simms** [comment]
@aj-stein-gsa I'm fascinated by responding this way! 🥇 Let me know if it makes sense to share the video concept brief with OSC while you're working on accessibility and integration issues. If not, I will standby. Many thanks!

**Comment by aj-stein-gsa** [comment]
@kyhu65867 worked on the table and I provided very minor feedback. @kyhu65867 if you read to pass back for another review, I defer to you.

**Comment by aj-stein-gsa** [comment]
Since we are in the middle of other things I am going to put this in "ready" state for us to pick up in the next time around.

**Comment by aj-stein-gsa** [comment]
We are going to park this work for now. It has been overcome by events, so the videos we recorded are quite likely to not be published in the future.
