### ISSUE TITLE
Align `prop` and  misc identifier requirements for the official FedRAMP namespace

### ISSUE THREAD

**Issue by aj-stein-gsa** [GSA/fedramp-automation#773]
### This is a ...

improvement - something could be better

### This relates to ...

- [ ] the **FedRAMP OSCAL Registry**
- [X] the **FedRAMP OSCAL baselines**
- [X] the **Guide to OSCAL-based FedRAMP Content**
- [X] the **Guide to OSCAL-based FedRAMP System Security Plans (SSP)**
- [X] the **Guide to OSCAL-based FedRAMP Security Assessment Plans (SAP)**
- [X] the **Guide to OSCAL-based FedRAMP Security Assessment Results (SAR)**
- [X] the **Guide to OSCAL-based FedRAMP Plan of Action and Milestones (POA&M)**
- [X] the **FedRAMP SSP OSCAL Template** (JSON or XML Format)
- [X] the **FedRAMP SAP OSCAL Template** (JSON or XML Format)
- [X] the **FedRAMP SAR OSCAL Template** (JSON or XML Format)
- [X] the **FedRAMP POA&M OSCAL Template** (JSON or XML Format)
- [X] the **FedRAMP OSCAL Validations**

### User Story

As a developer of OSCAL-based tools for FedRAMP documentation, I would like alignment on the properties `@ns`, `@system` and other identifier URIs that FedRAMP uses in different variations in their customization of the upstream custom models.

### Goals

- [ ] Document a uniform approach in a decision record (in #774)
- [ ] Review and update constraints accordingly (in #828) 
- [ ] Update website documentation accordingly (in GSA/automate.fedramp.gov/pull/102)
- [ ] Update baselines and examples accordingly  (in #828) 

### Dependencies

N/A

### Acceptance Criteria

- All FedRAMP Documents Related to OSCAL Adoption (https://github.com/GSA/fedramp-automation) affected by the changes in this issue have been updated.
- A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.

### Other information

1. Add reference to 774 PR for item 1 in goals

**Comment by aj-stein-gsa** [comment]
@Rene2mt volunteer to start this off for now and work on the ADR to start.

**Comment by Rene2mt** [comment]
Drafted the ADR (PR #774 ) but next, need to stage changes to constraints and add another PR for the documentation site.  Moving this back to in progress.

**Comment by Rene2mt** [comment]
@aj-stein-gsa we're going to keep this open for a bit and try to get feedback, so I didn't want to move it to "review".  The changes are small / simple but in a lot of places (the PRs touch a lot of files).  

Once we're ready, I'll rebase the associated PRs and formally move to "review".

**Comment by aj-stein-gsa** [comment]
> @aj-stein-gsa we're going to keep this open for a bit and try to get feedback, so I didn't want to move it to "review". The changes are small / simple but in a lot of places (the PRs touch a lot of files).
> 
> Once we're ready, I'll rebase the associated PRs and formally move to "review".

OK, got it. Sorry I read the email updates in the wrong order. 😆 Ignore my comment on #828 then.

**Comment by vmangat** [comment]
Consistency is good.

**Comment by Rene2mt** [comment]
Putting on hold for a few more days in case there is any final feedback after the upcoming OSCAL implementers.

**Comment by aj-stein-gsa** [comment]
@Rene2mt, I forgot to follow up after today's standup. I am giving you the go ahead to move this forward. Do you need help rebasing? Either way, let's discuss tomorrow.

**Comment by aj-stein-gsa** [comment]
The constraints have been deployed and website released. As discussed in the last month of meetings, we notified pilot participants [in the group mailing list](https://groups.google.com/a/gsa.gov/g/oscal-implementer/c/_myC_R3pSMY). I will be marking this as ready to ship.
