### ISSUE TITLE
Completeness Checks [EPIC]

### ISSUE THREAD

**Issue by brian-ruf** [GSA/fedramp-automation#803]
### This is a ...

fix - something needs to be different

### This relates to ...

- [ ] the **FedRAMP OSCAL Registry**
- [ ] the **FedRAMP OSCAL baselines**
- [X] the **Guide to OSCAL-based FedRAMP Content**
- [X] the **Guide to OSCAL-based FedRAMP System Security Plans (SSP)**
- [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Plans (SAP)**
- [ ] the **Guide to OSCAL-based FedRAMP Security Assessment Results (SAR)**
- [ ] the **Guide to OSCAL-based FedRAMP Plan of Action and Milestones (POA&M)**
- [X] the **FedRAMP SSP OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP SAP OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP SAR OSCAL Template** (JSON or XML Format)
- [ ] the **FedRAMP POA&M OSCAL Template** (JSON or XML Format)
- [X] the **FedRAMP OSCAL Validations**

### User Story

This reflects Stage 1A, SSP Completeness portion of the FedRAMP Automation Team's [Constraint Management Strategy](https://docs.google.com/document/d/1KrlSSrsD-JsFTevMfdA2IKgnlF_KYkpkoVdwGffwpOc/edit?usp=sharing) [Assess: FedRAMP only] for grouping and prioritizing constraint work.

Using the Legacy Word SSP Template as a reference, the FedRAMP Automation Team will work on SSP-related completeness checks that can be implemented via metaschema constraints in the following sequence and groupings:

- [ ] 

**Title Page  and Section 3 System Information:** 
**4 System Owner / 5 Assignment of Security Responsibility / Document Prep**
9 Services, Ports, and Protocols
6 Leveraged FedRAMP-Authorized Services
7 External Systems and Services Not Having FedRAMP Authorization
Appendix C, D, F, G, H, I, N, P <Insert CSO Name> Information Security Policies and Procedures
Appendix A FedRAMP Security Controls
8 Illustrated Architecture and Narratives
Appendix E  Digital Identity Worksheet
Appendix M Integrated Inventory Workbook (IIW)
Appendix K  Federal Information Processing Standard (FIPS) 199 Categorization
Appendix B Related Acronyms and L Specific Laws and Regulations

The following SSP template topic areas are deferred pending modeling and analysis work:
- 11	Separation of Duties: Defer this until the Separation of Duties matrix is properly modeled.
- Appendix Q <Insert CSO Name> Cryptographic Modules Table
- 10 Cryptographic Modules Implemented for Data At Rest (DAR)/Data In Transit (DIT)

The following SSP template topics will be generated, and will not have completeness checks:
- Appendix J <Insert CSO Name> Control Implementation Summary (CIS) and Customer Responsibilities Matrix (CRM) Workbook

OSCAL based SSPs and POA&Ms are treated as separate artifacts. As such, _Appendix O POA&M_ from the FedRAMP SSP Word template is not within the scope of SSP completeness checks and will instead be treated as a separate workstream under the constraint strategy.

### Goals

SSP Completeness checks are defined, tested and documented
