### ISSUE TITLE
Align with official release strategy and adjust constraints

### ISSUE THREAD

**Issue by aj-stein-gsa** [GSA/fedramp-automation#847]
### This relates to ...

- [X] the **FedRAMP OSCAL baselines**
- [X] the **Guide to OSCAL-based FedRAMP Content**
- [X] the **FedRAMP SAP OSCAL Template** (JSON or XML Format)
- [X] the **FedRAMP SAR OSCAL Template** (JSON or XML Format)
- [X] the **FedRAMP POA&M OSCAL Template** (JSON or XML Format)
- [X] the **FedRAMP OSCAL Validations**

### What happened?

During pairing on constraint develop around checking `fedramp-version` and `oscal-version`, colleagues reported that the [ADR#2 in repo version of our release strategy](https://github.com/GSA/fedramp-automation/blob/5cb73515d19b2fb8a56bf5f1a25f7d3c39dc30ec/documents/adr/0002-git-release-version-strategy.md) is not the same as our canonical updated version on the [website](https://automate.fedramp.gov/about/release/) (at this time from [`87a0d60`](https://github.com/GSA/automate.fedramp.gov/blob/87a0d609a1d7d102cceb23dfce877650f4b77459/content/about/release.md)). The latter was after much feedback from the community that the former had significant drawback. This was decided but not aligned, so we now need to align it. 

### What needs FedRAMP developer review?

- [x] #863
- [x] #866
- [x] GSA/automate.fedramp.gov#104 
- [x] https://github.com/GSA/automate.fedramp.gov/pull/114

### How do we replicate this issue?

1. Perform high-level review of this repo and the website.

### Where, exactly?

In multiple locations, see below.

### Other relevant details

Expected fixes:

- [x] Deprecate ADR2 and/or update it with a backported decision record. #866 
- [x] Update [the website page](https://automate.fedramp.gov/about/release/) with example tags to be actually semver, not `fedramp-3.0.0` per example. GSA/automate.fedramp.gov#104
- [x] Update [milestones with old version format](https://github.com/GSA/fedramp-automation/milestones) based on version in this repo.
- [x] Update wiki guidance on versioning in this repo. (Completed in wiki, [diff of the change](https://github.com/GSA/fedramp-automation/wiki/Release-Prep/_compare/95506b531b38bc11d70313ab52348c68b634e1d4...0cfdad7e68dee2f2ae37dba89fac418fa8eb082d).
- [x] Update recently merged constraint to check for "new" fedramp-version allowed-value correctly.
- [x] Redefine and move work in #618 and #833 accordingly and complete them.
